In [74]:
! pip install -q kaggle

In [75]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [76]:
!mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [77]:
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/

In [78]:
! chmod 600 ~/.kaggle/kaggle.json

In [79]:
! kaggle competitions download -c problem-3-prediction-of-cirrhosis-outcomes

problem-3-prediction-of-cirrhosis-outcomes.zip: Skipping, found more recently modified local copy (use --force to force download)

In [80]:
! unzip /content/problem-3-prediction-of-cirrhosis-outcomes.zip

Archive:  /content/problem-3-prediction-of-cirrhosis-outcomes.zip
replace sample_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [81]:
import pandas as pd
import numpy as np

In [82]:
tr=pd.read_csv('/content/train.csv')

In [83]:
te=pd.read_csv("/content/test.csv")

In [84]:
tr.head()

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,1087.0,NaN,19724.0,F,NaN,NaN,NaN,N,1.8,NaN,3.82,NaN,NaN,NaN,NaN,183.0,10.3,3.0,D
1,1,1443.0,NaN,14975.0,F,NaN,NaN,NaN,N,1.0,NaN,3.64,NaN,NaN,NaN,NaN,356.0,9.2,1.0,C
2,2,2855.0,NaN,19724.0,M,NaN,NaN,NaN,N,1.2,NaN,3.40,NaN,NaN,NaN,NaN,249.0,9.9,3.0,C
3,3,1654.0,NaN,21550.0,F,NaN,NaN,NaN,N,1.8,NaN,3.14,NaN,NaN,NaN,NaN,NaN,9.3,4.0,D
4,4,221.0,D-penicillamine,28018.0,F,Y,Y,Y,Y,21.6,261.0,2.43,155.0,1768.0,151.9,172.0,190.0,12.6,4.0,D

In [85]:
te.head()

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,15000,41.0,NaN,16071.0,F,NaN,NaN,NaN,N,3.3,NaN,3.75,NaN,NaN,NaN,NaN,160.0,11.1,4.0
1,15001,2580.0,D-penicillamine,15601.0,F,N,N,N,N,0.9,223.0,4.38,20.0,657.0,57.35,85.0,356.0,10.6,3.0
2,15002,3992.0,D-penicillamine,20440.0,F,N,N,N,N,0.6,273.0,3.20,22.0,423.0,49.60,67.0,445.0,9.6,3.0
3,15003,3021.0,NaN,15177.0,F,NaN,NaN,NaN,N,0.9,NaN,3.40,NaN,NaN,NaN,NaN,337.0,10.3,4.0
4,15004,1170.0,NaN,22646.0,F,NaN,NaN,NaN,N,0.6,NaN,3.78,NaN,NaN,NaN,NaN,209.0,10.8,2.0

In [86]:
tr.describe()

,id,N_Days,Age,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
count,15000.000000,15000.000000,15000.000000,15000.000000,6565.000000,15000.000000,8295.000000,8390.000000,8390.000000,6507.000000,14430.000000,14981.000000,15000.000000
mean,7499.500000,1957.803733,19355.880067,1.837787,324.009901,3.526019,73.971911,1655.571692,104.676073,109.451514,254.856124,10.618881,3.029400
std,4330.271354,1369.985666,3888.952325,2.710927,172.808687,0.371056,72.273416,1905.740702,48.544351,49.120068,101.063266,0.728713,0.879197
min,0.000000,28.000000,820.000000,0.300000,53.000000,1.800000,1.000000,14.100000,12.300000,33.000000,2.870000,0.600000,1.000000
25%,3749.750000,1092.000000,16728.000000,0.600000,239.000000,3.290000,31.000000,705.000000,70.000000,78.000000,190.000000,10.100000,2.000000
50%,7499.500000,1769.000000,19724.000000,0.900000,280.000000,3.580000,52.000000,1062.000000,97.650000,99.000000,251.000000,10.600000,3.000000
75%,11249.250000,2598.000000,22347.000000,1.800000,360.000000,3.770000,86.000000,1637.000000,130.200000,131.000000,312.000000,11.000000,4.000000
max,14999.000000,25772.000000,189992.000000,28.000000,2176.000000,5.500000,598.000000,25772.800000,601.450000,598.000000,4190.000000,18.000000,4.000000

In [87]:
tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             15000 non-null  int64
 1   N_Days         15000 non-null  float64
 2   Drug           8402 non-null   object
 3   Age            15000 non-null  float64
 4   Sex            15000 non-null  object
 5   Ascites        8403 non-null   object
 6   Hepatomegaly   8393 non-null   object
 7   Spiders        8392 non-null   object
 8   Edema          15000 non-null  object
 9   Bilirubin      15000 non-null  float64
 10  Cholesterol    6565 non-null   float64
 11  Albumin        15000 non-null  float64
 12  Copper         8295 non-null   float64
 13  Alk_Phos       8390 non-null   float64
 14  SGOT           8390 non-null   float64
 15  Tryglicerides  6507 non-null   float64
 16  Platelets      14430 non-null  float64
 17  Prothrombin    14981 non-null  float64
 18  Stage          15000 non-null  float64
 19  Status         15000 non-null  object
dtypes: float64(12), int64(1), object(7)
memory usage: 2.3+ MB

In [88]:
frames = [tr,te]
df = pd.concat(frames)

In [89]:
df.head()

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,1087.0,NaN,19724.0,F,NaN,NaN,NaN,N,1.8,NaN,3.82,NaN,NaN,NaN,NaN,183.0,10.3,3.0,D
1,1,1443.0,NaN,14975.0,F,NaN,NaN,NaN,N,1.0,NaN,3.64,NaN,NaN,NaN,NaN,356.0,9.2,1.0,C
2,2,2855.0,NaN,19724.0,M,NaN,NaN,NaN,N,1.2,NaN,3.40,NaN,NaN,NaN,NaN,249.0,9.9,3.0,C
3,3,1654.0,NaN,21550.0,F,NaN,NaN,NaN,N,1.8,NaN,3.14,NaN,NaN,NaN,NaN,NaN,9.3,4.0,D
4,4,221.0,D-penicillamine,28018.0,F,Y,Y,Y,Y,21.6,261.0,2.43,155.0,1768.0,151.9,172.0,190.0,12.6,4.0,D

In [90]:
df.tail()

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
9995,24995,2772.0,Placebo,15119.0,F,N,N,N,N,0.6,360.0,4.01,39.0,1472.0,134.00,154.0,200.0,10.5,2.0,NaN
9996,24996,1236.0,Placebo,22156.0,F,N,Y,N,N,3.2,298.0,3.83,38.0,1212.0,151.90,102.0,295.0,10.0,2.0,NaN
9997,24997,2812.0,NaN,18628.0,F,NaN,NaN,NaN,S,0.9,NaN,3.92,NaN,NaN,NaN,NaN,NaN,9.5,4.0,NaN
9998,24998,611.0,Placebo,26259.0,M,N,Y,N,N,2.3,227.0,3.04,62.0,5396.0,221.88,91.0,234.0,9.9,2.0,NaN
9999,24999,617.0,NaN,17525.0,F,NaN,NaN,NaN,N,1.8,NaN,3.13,NaN,NaN,NaN,NaN,165.0,10.6,3.0,NaN

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             25000 non-null  int64
 1   N_Days         25000 non-null  float64
 2   Drug           13970 non-null  object
 3   Age            25000 non-null  float64
 4   Sex            25000 non-null  object
 5   Ascites        13969 non-null  object
 6   Hepatomegaly   13959 non-null  object
 7   Spiders        13953 non-null  object
 8   Edema          25000 non-null  object
 9   Bilirubin      24999 non-null  float64
 10  Cholesterol    10946 non-null  float64
 11  Albumin        25000 non-null  float64
 12  Copper         13788 non-null  float64
 13  Alk_Phos       13951 non-null  float64
 14  SGOT           13953 non-null  float64
 15  Tryglicerides  10869 non-null  float64
 16  Platelets      24057 non-null  float64
 17  Prothrombin    24966 non-null  float64
 18  Stage          25000 non-null  float64
 19  Status         15000 non-null  object
dtypes: float64(12), int64(1), object(7)
memory usage: 4.0+ MB

In [92]:
df

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,1087.0,NaN,19724.0,F,NaN,NaN,NaN,N,1.8,NaN,3.82,NaN,NaN,NaN,NaN,183.0,10.3,3.0,D
1,1,1443.0,NaN,14975.0,F,NaN,NaN,NaN,N,1.0,NaN,3.64,NaN,NaN,NaN,NaN,356.0,9.2,1.0,C
2,2,2855.0,NaN,19724.0,M,NaN,NaN,NaN,N,1.2,NaN,3.40,NaN,NaN,NaN,NaN,249.0,9.9,3.0,C
3,3,1654.0,NaN,21550.0,F,NaN,NaN,NaN,N,1.8,NaN,3.14,NaN,NaN,NaN,NaN,NaN,9.3,4.0,D
4,4,221.0,D-penicillamine,28018.0,F,Y,Y,Y,Y,21.6,261.0,2.43,155.0,1768.0,151.90,172.0,190.0,12.6,4.0,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,24995,2772.0,Placebo,15119.0,F,N,N,N,N,0.6,360.0,4.01,39.0,1472.0,134.00,154.0,200.0,10.5,2.0,NaN
9996,24996,1236.0,Placebo,22156.0,F,N,Y,N,N,3.2,298.0,3.83,38.0,1212.0,151.90,102.0,295.0,10.0,2.0,NaN
9997,24997,2812.0,NaN,18628.0,F,NaN,NaN,NaN,S,0.9,NaN,3.92,NaN,NaN,NaN,NaN,NaN,9.5,4.0,NaN
9998,24998,611.0,Placebo,26259.0,M,N,Y,N,N,2.3,227.0,3.04,62.0,5396.0,221.88,91.0,234.0,9.9,2.0,NaN
9999,24999,617.0,NaN,17525.0,F,NaN,NaN,NaN,N,1.8,NaN,3.13,NaN,NaN,NaN,NaN,165.0,10.6,3.0,NaN

In [93]:
df["Drug"].value_counts()

Drug
D-penicillamine    7416
Placebo            6553
Drug                  1
Name: count, dtype: int64

In [94]:
te["Drug"].value_counts()

Drug
D-penicillamine    2923
Placebo            2644
Drug                  1
Name: count, dtype: int64

In [95]:
df

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,1087.0,NaN,19724.0,F,NaN,NaN,NaN,N,1.8,NaN,3.82,NaN,NaN,NaN,NaN,183.0,10.3,3.0,D
1,1,1443.0,NaN,14975.0,F,NaN,NaN,NaN,N,1.0,NaN,3.64,NaN,NaN,NaN,NaN,356.0,9.2,1.0,C
2,2,2855.0,NaN,19724.0,M,NaN,NaN,NaN,N,1.2,NaN,3.40,NaN,NaN,NaN,NaN,249.0,9.9,3.0,C
3,3,1654.0,NaN,21550.0,F,NaN,NaN,NaN,N,1.8,NaN,3.14,NaN,NaN,NaN,NaN,NaN,9.3,4.0,D
4,4,221.0,D-penicillamine,28018.0,F,Y,Y,Y,Y,21.6,261.0,2.43,155.0,1768.0,151.90,172.0,190.0,12.6,4.0,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,24995,2772.0,Placebo,15119.0,F,N,N,N,N,0.6,360.0,4.01,39.0,1472.0,134.00,154.0,200.0,10.5,2.0,NaN
9996,24996,1236.0,Placebo,22156.0,F,N,Y,N,N,3.2,298.0,3.83,38.0,1212.0,151.90,102.0,295.0,10.0,2.0,NaN
9997,24997,2812.0,NaN,18628.0,F,NaN,NaN,NaN,S,0.9,NaN,3.92,NaN,NaN,NaN,NaN,NaN,9.5,4.0,NaN
9998,24998,611.0,Placebo,26259.0,M,N,Y,N,N,2.3,227.0,3.04,62.0,5396.0,221.88,91.0,234.0,9.9,2.0,NaN
9999,24999,617.0,NaN,17525.0,F,NaN,NaN,NaN,N,1.8,NaN,3.13,NaN,NaN,NaN,NaN,165.0,10.6,3.0,NaN

In [96]:
df["Sex"].value_counts()

Sex
F    23950
M     1050
Name: count, dtype: int64

In [97]:
df["Status"].value_counts()

Status
C     10170
D      4444
CL      386
Name: count, dtype: int64

In [98]:
df.isnull().sum()

id                   0
N_Days               0
Drug             11030
Age                  0
Sex                  0
Ascites          11031
Hepatomegaly     11041
Spiders          11047
Edema                0
Bilirubin            1
Cholesterol      14054
Albumin              0
Copper           11212
Alk_Phos         11049
SGOT             11047
Tryglicerides    14131
Platelets          943
Prothrombin         34
Stage                0
Status           10000
dtype: int64

In [99]:
df.dropna(inplace=True)

In [100]:
df.isnull().sum()

id               0
N_Days           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
Status           0
dtype: int64

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6253 entries, 4 to 14994
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             6253 non-null   int64
 1   N_Days         6253 non-null   float64
 2   Drug           6253 non-null   object
 3   Age            6253 non-null   float64
 4   Sex            6253 non-null   object
 5   Ascites        6253 non-null   object
 6   Hepatomegaly   6253 non-null   object
 7   Spiders        6253 non-null   object
 8   Edema          6253 non-null   object
 9   Bilirubin      6253 non-null   float64
 10  Cholesterol    6253 non-null   float64
 11  Albumin        6253 non-null   float64
 12  Copper         6253 non-null   float64
 13  Alk_Phos       6253 non-null   float64
 14  SGOT           6253 non-null   float64
 15  Tryglicerides  6253 non-null   float64
 16  Platelets      6253 non-null   float64
 17  Prothrombin    6253 non-null   float64
 18  Stage          6253 non-null   float64
 19  Status         6253 non-null   object
dtypes: float64(12), int64(1), object(7)
memory usage: 1.0+ MB

In [102]:
tr.shape

(15000, 20)

In [103]:
te.shape

(10000, 19)

In [104]:
tr.shape

(15000, 20)

In [105]:
te.shape

(10000, 19)

In [106]:
tr

,id,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,0,1087.0,NaN,19724.0,F,NaN,NaN,NaN,N,1.8,NaN,3.82,NaN,NaN,NaN,NaN,183.0,10.3,3.0,D
1,1,1443.0,NaN,14975.0,F,NaN,NaN,NaN,N,1.0,NaN,3.64,NaN,NaN,NaN,NaN,356.0,9.2,1.0,C
2,2,2855.0,NaN,19724.0,M,NaN,NaN,NaN,N,1.2,NaN,3.40,NaN,NaN,NaN,NaN,249.0,9.9,3.0,C
3,3,1654.0,NaN,21550.0,F,NaN,NaN,NaN,N,1.8,NaN,3.14,NaN,NaN,NaN,NaN,NaN,9.3,4.0,D
4,4,221.0,D-penicillamine,28018.0,F,Y,Y,Y,Y,21.6,261.0,2.43,155.0,1768.0,151.90,172.0,190.0,12.6,4.0,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14995,1097.0,NaN,22646.0,F,NaN,NaN,NaN,N,2.1,NaN,4.01,NaN,NaN,NaN,NaN,142.0,10.8,2.0,C
14996,14996,1000.0,D-penicillamine,24622.0,F,N,Y,N,N,1.3,NaN,3.80,94.0,6456.2,56.76,NaN,214.0,11.0,4.0,D
14997,14997,4214.0,NaN,17897.0,F,NaN,NaN,NaN,N,13.8,NaN,3.01,NaN,NaN,NaN,NaN,388.0,NaN,3.0,D
14998,14998,1654.0,NaN,16071.0,F,NaN,NaN,NaN,N,0.7,NaN,3.40,NaN,NaN,NaN,NaN,330.0,10.3,3.0,C
14999,14999,786.0,D-penicillamine,19884.0,F,N,N,Y,N,0.6,NaN,3.65,94.0,6456.2,56.00,NaN,344.0,10.9,4.0,D

In [107]:
x_train=tr.drop(columns=["id","Status"])

In [108]:
y_train=tr["Status"]

In [109]:
x_train

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1087.0,NaN,19724.0,F,NaN,NaN,NaN,N,1.8,NaN,3.82,NaN,NaN,NaN,NaN,183.0,10.3,3.0
1,1443.0,NaN,14975.0,F,NaN,NaN,NaN,N,1.0,NaN,3.64,NaN,NaN,NaN,NaN,356.0,9.2,1.0
2,2855.0,NaN,19724.0,M,NaN,NaN,NaN,N,1.2,NaN,3.40,NaN,NaN,NaN,NaN,249.0,9.9,3.0
3,1654.0,NaN,21550.0,F,NaN,NaN,NaN,N,1.8,NaN,3.14,NaN,NaN,NaN,NaN,NaN,9.3,4.0
4,221.0,D-penicillamine,28018.0,F,Y,Y,Y,Y,21.6,261.0,2.43,155.0,1768.0,151.90,172.0,190.0,12.6,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,1097.0,NaN,22646.0,F,NaN,NaN,NaN,N,2.1,NaN,4.01,NaN,NaN,NaN,NaN,142.0,10.8,2.0
14996,1000.0,D-penicillamine,24622.0,F,N,Y,N,N,1.3,NaN,3.80,94.0,6456.2,56.76,NaN,214.0,11.0,4.0
14997,4214.0,NaN,17897.0,F,NaN,NaN,NaN,N,13.8,NaN,3.01,NaN,NaN,NaN,NaN,388.0,NaN,3.0
14998,1654.0,NaN,16071.0,F,NaN,NaN,NaN,N,0.7,NaN,3.40,NaN,NaN,NaN,NaN,330.0,10.3,3.0
14999,786.0,D-penicillamine,19884.0,F,N,N,Y,N,0.6,NaN,3.65,94.0,6456.2,56.00,NaN,344.0,10.9,4.0

In [110]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x_train["Drug"]=le.fit_transform(x_train["Drug"])
x_train["Sex"]=le.fit_transform(x_train["Sex"])
x_train["Ascites"]=le.fit_transform(x_train["Ascites"])
x_train["Hepatomegaly"]=le.fit_transform(x_train["Hepatomegaly"])
x_train["Spiders"]=le.fit_transform(x_train["Spiders"])
x_train["Edema"]=le.fit_transform(x_train["Edema"])

In [111]:
x_train

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1087.0,2,19724.0,0,3,4,2,0,1.8,NaN,3.82,NaN,NaN,NaN,NaN,183.0,10.3,3.0
1,1443.0,2,14975.0,0,3,4,2,0,1.0,NaN,3.64,NaN,NaN,NaN,NaN,356.0,9.2,1.0
2,2855.0,2,19724.0,1,3,4,2,0,1.2,NaN,3.40,NaN,NaN,NaN,NaN,249.0,9.9,3.0
3,1654.0,2,21550.0,0,3,4,2,0,1.8,NaN,3.14,NaN,NaN,NaN,NaN,NaN,9.3,4.0
4,221.0,0,28018.0,0,2,3,1,2,21.6,261.0,2.43,155.0,1768.0,151.90,172.0,190.0,12.6,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,1097.0,2,22646.0,0,3,4,2,0,2.1,NaN,4.01,NaN,NaN,NaN,NaN,142.0,10.8,2.0
14996,1000.0,0,24622.0,0,1,3,0,0,1.3,NaN,3.80,94.0,6456.2,56.76,NaN,214.0,11.0,4.0
14997,4214.0,2,17897.0,0,3,4,2,0,13.8,NaN,3.01,NaN,NaN,NaN,NaN,388.0,NaN,3.0
14998,1654.0,2,16071.0,0,3,4,2,0,0.7,NaN,3.40,NaN,NaN,NaN,NaN,330.0,10.3,3.0
14999,786.0,0,19884.0,0,1,2,1,0,0.6,NaN,3.65,94.0,6456.2,56.00,NaN,344.0,10.9,4.0

In [112]:
y_train

0        D
1        C
2        C
3        D
4        D
        ..
14995    C
14996    D
14997    D
14998    C
14999    D
Name: Status, Length: 15000, dtype: object

In [113]:
y_train.value_counts()

Status
C     10170
D      4444
CL      386
Name: count, dtype: int64

In [114]:
#dummies= pd.get_dummies(y_train)
#y_train=dummies.copy()

In [115]:
y_train

0        D
1        C
2        C
3        D
4        D
        ..
14995    C
14996    D
14997    D
14998    C
14999    D
Name: Status, Length: 15000, dtype: object

In [116]:
#y_train["C"]=y_train["C"].astype(int)
#y_train["D"]=y_train["D"].astype(int)
#y_train["CL"]=y_train["CL"].astype(int)

In [117]:
y_train=y_train.map({"C":0,"D":1,"CL":2})
y_train

0        1
1        0
2        0
3        1
4        1
        ..
14995    0
14996    1
14997    1
14998    0
14999    1
Name: Status, Length: 15000, dtype: int64

In [118]:
#y_train_c=y_train["C"]
#y_train_d=y_train["D"]
#y_train_cl=y_train["CL"]

In [119]:
from sklearn.linear_model import LogisticRegression

In [120]:
log = LogisticRegression(max_iter=1000, random_state=1)
log.fit(x_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
te

In [ ]:
te["Drug"]=le.fit_transform(te["Drug"])
te["Sex"]=le.fit_transform(te["Sex"])
te["Ascites"]=le.fit_transform(te["Ascites"])
te["Hepatomegaly"]=le.fit_transform(te["Hepatomegaly"])
te["Spiders"]=le.fit_transform(te["Spiders"])
te["Edema"]=le.fit_transform(te["Edema"])

In [ ]:
te

In [ ]:
te.shape

In [ ]:
te=te.drop(columns=["id"])

In [ ]:
te.isnull().sum()