In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import MinMaxScaler

In [127]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [128]:
train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [129]:
test

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [130]:
df=pd.concat([train,test],axis=0)

In [131]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [132]:
print(df.isnull().sum())

PassengerId        0
HomePlanet       288
CryoSleep        310
Cabin            299
Destination      274
Age              270
VIP              296
RoomService      263
FoodCourt        289
ShoppingMall     306
Spa              284
VRDeck           268
Name             294
Transported     4277
dtype: int64

In [133]:
df['HomePlanet'].fillna(df['HomePlanet'].mode()[0], inplace=True)  # Fill with mode
df['CryoSleep'].fillna(0, inplace=True)  # Fill with 0 (assuming False)
df['Cabin'].fillna('Unknown', inplace=True)  # Fill with placeholder
df['Destination'].fillna(df['Destination'].mode()[0], inplace=True)  # Fill with mode
df['Age'].fillna(df['Age'].median(), inplace=True)  # Fill with median
df['VIP'].fillna(0, inplace=True)  # Fill with 0 (assuming False)
df['RoomService'].fillna(df['RoomService'].median(), inplace=True)  # Fill with median
df['FoodCourt'].fillna(0, inplace=True)  # Fill with 0
df['ShoppingMall'].fillna(0, inplace=True)  # Fill with 0
df['Spa'].fillna(df['Spa'].median(), inplace=True)  # Fill with median
df['VRDeck'].fillna(df['VRDeck'].median(), inplace=True)  # Fill with median
df['Name'].fillna('Unknown', inplace=True)  # Fill with placeholder

<ipython-input-133-acf205d1d3f4>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['HomePlanet'].fillna(df['HomePlanet'].mode()[0], inplace=True)  # Fill with mode
<ipython-input-133-acf205d1d3f4>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CryoSleep'].fillna(0, inplace=True)  # Fill with 0 (assuming False)
<ipython-input-133-acf205d1d3f4>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna('Unknown', inplace=True)  # Fill with placeholder
<ipython-input-133-acf205d1d3f4>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Destination'].fillna(df['Destination'].mode()[0], inplace=True)  # Fill with mode
<ipython-input-133-acf205d1d3f4>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)  # Fill with median
<ipython-input-133-acf205d1d3f4>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['VIP'].fillna(0, inplace=True)  # Fill with 0 (assuming False)
<ipython-input-133-acf205d1d3f4>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RoomService'].fillna(df['RoomService'].median(), inplace=True)  # Fill with median
<ipython-input-133-acf205d1d3f4>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FoodCourt'].fillna(0, inplace=True)  # Fill with 0
<ipython-input-133-acf205d1d3f4>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ShoppingMall'].fillna(0, inplace=True)  # Fill with 0
<ipython-input-133-acf205d1d3f4>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Spa'].fillna(df['Spa'].median(), inplace=True)  # Fill with median
<ipython-input-133-acf205d1d3f4>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['VRDeck'].fillna(df['VRDeck'].median(), inplace=True)  # Fill with median
<ipython-input-133-acf205d1d3f4>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Name'].fillna('Unknown', inplace=True)  # Fill with placeholder

In [134]:
df.isnull().sum()

PassengerId        0
HomePlanet         0
CryoSleep          0
Cabin              0
Destination        0
Age                0
VIP                0
RoomService        0
FoodCourt          0
ShoppingMall       0
Spa                0
VRDeck             0
Name               0
Transported     4277
dtype: int64

In [135]:
df

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter,NaN
4273,9269_01,Earth,False,Unknown,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron,NaN
4274,9271_01,Mars,True,D/296/P,55 Cancri e,27.0,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore,NaN
4275,9273_01,Europa,False,D/297/P,TRAPPIST-1e,27.0,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale,NaN
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley,NaN

In [136]:
categorical_cols = ['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP', 'Name']
label_encoder = LabelEncoder()

In [137]:
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [138]:
df

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,1,0,208,2,39.0,0,0.0,0.0,0.0,0.0,0.0,7819,False
1,0002_01,0,0,3241,2,24.0,0,109.0,9.0,25.0,549.0,44.0,6688,True
2,0003_01,1,0,1,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,669,False
3,0003_02,1,0,1,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,10688,False
4,0004_01,0,0,3243,2,16.0,0,303.0,70.0,151.0,565.0,2.0,12401,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,0,1,7956,2,34.0,0,0.0,0.0,0.0,0.0,0.0,6381,NaN
4273,9269_01,0,0,9825,2,42.0,0,0.0,847.0,17.0,10.0,144.0,8047,NaN
4274,9271_01,2,1,1905,0,27.0,0,0.0,0.0,0.0,0.0,0.0,6301,NaN
4275,9273_01,1,0,1906,2,27.0,0,0.0,2680.0,0.0,0.0,523.0,7032,NaN
4276,9277_01,0,1,7960,1,43.0,0,0.0,0.0,0.0,0.0,0.0,7406,NaN

In [139]:
scaler = MinMaxScaler()

In [140]:
numeric_cols = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck','Cabin']
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [141]:
df

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,1,0,0.021170,2,0.493671,0,0.000000,0.000000,0.000000,0.000000,0.000000,7819,False
1,0002_01,0,0,0.329873,2,0.303797,0,0.007608,0.000302,0.001064,0.024500,0.001823,6688,True
2,0003_01,1,0,0.000102,2,0.734177,1,0.003001,0.119948,0.000000,0.299670,0.002030,669,False
3,0003_02,1,0,0.000102,2,0.417722,0,0.000000,0.043035,0.015793,0.148563,0.007997,10688,False
4,0004_01,0,0,0.330076,2,0.202532,0,0.021149,0.002348,0.006428,0.025214,0.000083,12401,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,0,1,0.809771,2,0.430380,0,0.000000,0.000000,0.000000,0.000000,0.000000,6381,NaN
4273,9269_01,0,0,1.000000,2,0.531646,0,0.000000,0.028410,0.000724,0.000446,0.005967,8047,NaN
4274,9271_01,2,1,0.193893,0,0.341772,0,0.000000,0.000000,0.000000,0.000000,0.000000,6301,NaN
4275,9273_01,1,0,0.193995,2,0.341772,0,0.000000,0.089894,0.000000,0.000000,0.021672,7032,NaN
4276,9277_01,0,1,0.810178,1,0.544304,0,0.000000,0.000000,0.000000,0.000000,0.000000,7406,NaN

In [142]:
train = df.iloc[:8693]  # Use df.iloc to access rows by position
test = df.iloc[8693:]   # Use df.iloc to access rows by position

In [143]:
train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,1,0,0.021170,2,0.493671,0,0.000000,0.000000,0.000000,0.000000,0.000000,7819,False
1,0002_01,0,0,0.329873,2,0.303797,0,0.007608,0.000302,0.001064,0.024500,0.001823,6688,True
2,0003_01,1,0,0.000102,2,0.734177,1,0.003001,0.119948,0.000000,0.299670,0.002030,669,False
3,0003_02,1,0,0.000102,2,0.417722,0,0.000000,0.043035,0.015793,0.148563,0.007997,10688,False
4,0004_01,0,0,0.330076,2,0.202532,0,0.021149,0.002348,0.006428,0.025214,0.000083,12401,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,1,0,0.020865,0,0.518987,1,0.000000,0.228726,0.000000,0.073322,0.003066,5252,False
8689,9278_01,0,1,0.810382,1,0.227848,0,0.000000,0.000000,0.000000,0.000000,0.000000,7124,False
8690,9279_01,0,0,0.810992,2,0.329114,0,0.000000,0.000000,0.079687,0.000045,0.000000,4498,True
8691,9280_01,1,0,0.321323,0,0.405063,0,0.000000,0.035186,0.000000,0.015753,0.134049,2389,False
8692,9280_02,1,0,0.321323,2,0.556962,0,0.008795,0.157247,0.000000,0.000000,0.000497,9502,True

In [144]:
test

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0013_01,0,1,0.844580,2,0.341772,0,0.000000,0.000000,0.000000,0.000000,0.000000,8814,NaN
1,0018_01,0,0,0.566310,2,0.240506,0,0.000000,0.000302,0.000000,0.125982,0.000000,7310,NaN
2,0019_01,1,1,0.087125,0,0.392405,0,0.000000,0.000000,0.000000,0.000000,0.000000,10131,NaN
3,0021_01,1,0,0.087328,2,0.481013,0,0.000000,0.223124,0.000000,0.008077,0.024241,8202,NaN
4,0023_01,0,0,0.588804,2,0.253165,0,0.000698,0.000000,0.027030,0.000000,0.000000,1996,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,0,1,0.809771,2,0.430380,0,0.000000,0.000000,0.000000,0.000000,0.000000,6381,NaN
4273,9269_01,0,0,1.000000,2,0.531646,0,0.000000,0.028410,0.000724,0.000446,0.005967,8047,NaN
4274,9271_01,2,1,0.193893,0,0.341772,0,0.000000,0.000000,0.000000,0.000000,0.000000,6301,NaN
4275,9273_01,1,0,0.193995,2,0.341772,0,0.000000,0.089894,0.000000,0.000000,0.021672,7032,NaN
4276,9277_01,0,1,0.810178,1,0.544304,0,0.000000,0.000000,0.000000,0.000000,0.000000,7406,NaN

In [145]:
x=train.drop('Transported',axis=1)
y=train['Transported']

In [146]:
y=y.astype(int)

In [147]:
y

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int64

In [148]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=102)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=102)

In [149]:
y_pred = rf_model.predict(X_test)

In [150]:
print("Random Forest Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ROC AUC Score
roc_auc = roc_auc_score(y_test, rf_model.predict_proba(X_test)[:, 1])
print(f"ROC AUC Score: {roc_auc:.4f}")

Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.78      0.78       861
           1       0.78      0.78      0.78       878

    accuracy                           0.78      1739
   macro avg       0.78      0.78      0.78      1739
weighted avg       0.78      0.78      0.78      1739

Confusion Matrix:
[[670 191]
 [197 681]]
ROC AUC Score: 0.8706

In [151]:
test=test.drop('Transported',axis=1)

In [152]:
y_pred1=rf_model.predict(test)

In [153]:
y_pred1

array([1, 0, 1, ..., 1, 1, 0])

In [154]:
Transported=pd.DataFrame(y_pred1)

In [155]:
Transported

      0
0     1
1     0
2     1
3     1
4     1
...  ..
4272  1
4273  0
4274  1
4275  1
4276  0

[4277 rows x 1 columns]

In [156]:
dict={0:'False',1:'True'}
Transported['Transported']=Transported[0].map(dict)

In [157]:
Transported

      0 Transported
0     1        True
1     0       False
2     1        True
3     1        True
4     1        True
...  ..         ...
4272  1        True
4273  0       False
4274  1        True
4275  1        True
4276  0       False

[4277 rows x 2 columns]

In [158]:
new=test['PassengerId']

In [159]:
new

0       0013_01
1       0018_01
2       0019_01
3       0021_01
4       0023_01
         ...
4272    9266_02
4273    9269_01
4274    9271_01
4275    9273_01
4276    9277_01
Name: PassengerId, Length: 4277, dtype: object

In [160]:
submission = pd.DataFrame({'PassengerId': test['PassengerId'], 'Transported': Transported['Transported']})

In [161]:
submission

     PassengerId Transported
0        0013_01        True
1        0018_01       False
2        0019_01        True
3        0021_01        True
4        0023_01        True
...          ...         ...
4272     9266_02        True
4273     9269_01       False
4274     9271_01        True
4275     9273_01        True
4276     9277_01       False

[4277 rows x 2 columns]

In [162]:
submission.to_csv('submission.csv', index=False)