In [588]:
! pip install -q kaggle

In [589]:
#from google.colab import files

#files.upload()

In [590]:
! mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [591]:
! cp kaggle.json ~/.kaggle/

In [592]:
! chmod 600 ~/.kaggle/kaggle.json

In [593]:
! kaggle datasets list #fetch the list of Datasets from Kaggle

ref                                                              title                                                size  lastUpdated          downloadCount  voteCount  usabilityRating
---------------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------  ---------  ---------------
lainguyn123/student-performance-factors                          Student Performance Factors                          94KB  2024-09-02 10:53:57           6360        143  1.0
hanaksoy/customer-purchasing-behaviors                           Customer Purchasing Behaviors                         1KB  2024-09-01 22:18:07           3763         53  1.0
haseebindata/student-performance-predictions                     Student Performance Predictions                       9KB  2024-08-17 06:57:57          11740        249  0.9411765
computingvictor/2024-academic-ranking-of-world-universities      🥇 Top Universities Ranking 2024                      19KB  2024-08-20 11:54:54           1960         39  1.0
abdullah0a/retail-sales-data-with-seasonal-trends-and-marketing  Retail Sales Data with Seasonal Trends & Marketing  320KB  2024-09-09 07:02:46           1890         37  1.0
waqi786/climate-change-impact-on-agriculture                     🌍 Climate Change Impact on Agriculture 🌱            327KB  2024-09-06 13:25:59           1998         38  1.0
thebumpkin/300-world-music-tracks-with-spotify-data              300 World Music Tracks (with Spotify Data)           19KB  2024-08-25 13:05:14           1625         26  1.0
muhammadehsan02/formula-1-world-championship-history-1950-2024   Formula 1 World Championship History (1950-2024)      6MB  2024-09-03 20:11:24           1356         31  1.0
thebumpkin/10400-classic-hits-10-genres-1923-to-2023             15,000 Music Tracks - 19 Genres (w/ Spotify Data)   677KB  2024-08-30 18:20:48           1177         25  1.0
uom190346a/ai-powered-job-market-insights                        AI-Powered Job Market Insights                       10KB  2024-08-26 05:55:43           4247         80  1.0
marius2303/ad-click-prediction-dataset                            📣 Ad Click Prediction Dataset                       81KB  2024-09-07 13:08:11           1096         28  1.0
muhammadehsan02/126-years-of-historical-olympic-dataset          126 Years of Historical Olympic Dataset              27MB  2024-08-27 12:51:57           1827         41  1.0
michaelmatta0/amazon-cell-phones-cleaned-scraped-data            Amazon Cell Phones Cleaned Scraped Data               2MB  2024-09-10 21:01:15            888         25  1.0
abdullah0a/human-age-prediction-synthetic-dataset                Human Age Prediction Synthetic Dataset              739KB  2024-09-04 07:25:39           2121         35  1.0
mbsoroush/google-dataset                                         Google Dataset                                       29KB  2024-09-06 03:09:40            354         23  1.0
abdullahashfaqvirk/student-mental-health-survey                  Student Mental Health Survey                          2KB  2024-08-23 15:38:57           4712         73  0.88235295
novandraanugrah/bitcoin-historical-datasets-2018-2024            BITCOIN Historical Datasets 2018-2024                17MB  2024-09-09 01:19:56           1084         36  1.0
muhammadehsan02/olympic-summer-games-paris-2024                  Olympic Summer Games - Paris 2024                     3MB  2024-08-24 18:51:30           2006         33  1.0
stefanydeoliveira/summer-olympics-medals-1896-2024               Summer Olympics Medals (1896-2024)                    4MB  2024-08-29 23:52:10           2309         46  1.0
berkayalan/paris-2024-olympics-medals                            Paris 2024 Olympics Medals                            1KB  2024-08-14 11:02:45           6965        116  1.0

In [594]:
! kaggle competitions download -c problem-4-tweet-classification

problem-4-tweet-classification.zip: Skipping, found more recently modified local copy (use --force to force download)

In [595]:
# ! unzip /content/problem-4-tweet-classification.zip

In [596]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download required resources from nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Initialize stemming and lemmatization
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [597]:
train=pd.read_csv("/content/train.csv")
test=pd.read_csv("/content/test.csv")
df=pd.concat([train,test])
df.head()

   Id  Category                                              Tweet
0   1   neutral  Zlatan's 20th goal of the season not enough fo...
1   2  positive  Zlatan wears sunglasses so his eyes do not har...
2   3  positive  Zlatan to Milan may not be the best thing for ...
3   4  positive  Zlatan says he may have played his last match ...
4   5  positive  Zlatan is still a beast. If he's replacing RvP...

In [598]:
train.shape,test.shape,df.shape

((5000, 3), (422, 2), (5422, 3))

In [599]:
df.tail()

       Id Category                                              Tweet
417  5418      NaN  "@AnishJain50: Sting opens Monday night Raw! #...
418  5419      NaN  "...bizarre rituals intended to bring about th...
419  5420      NaN  "...and the sun became as black as sackcloth. ...
420  5421      NaN  "#Denali, the great one soaring under the midn...
421  5422      NaN  - Just found out season 3 of Arrow is going to...

In [600]:
df["Category"].value_counts()

Category
positive    2393
neutral     1794
negative     812
Tweet          1
Name: count, dtype: int64

In [601]:
df.shape

(5422, 3)

In [602]:
df.isnull().sum()

Id            0
Category    422
Tweet         0
dtype: int64

In [603]:
df.dtypes

Id           int64
Category    object
Tweet       object
dtype: object

In [604]:
df['edited_text'] = df['Tweet'].apply(lambda x: ' '.join([stemmer.stem(word) for word in word_tokenize(x)]))

In [605]:
df

,Id,Category,Tweet,edited_text
0,1,neutral,Zlatan's 20th goal of the season not enough fo...,zlatan 's 20th goal of the season not enough f...
1,2,positive,Zlatan wears sunglasses so his eyes do not har...,zlatan wear sunglass so hi eye do not harm the...
2,3,positive,Zlatan to Milan may not be the best thing for ...,zlatan to milan may not be the best thing for ...
3,4,positive,Zlatan says he may have played his last match ...,zlatan say he may have play hi last match for ...
4,5,positive,Zlatan is still a beast. If he's replacing RvP...,zlatan is still a beast . if he 's replac rvp ...
...,...,...,...,...
417,5418,NaN,"""@AnishJain50: Sting opens Monday night Raw! #...",`` @ anishjain50 : sting open monday night raw...
418,5419,NaN,"""...bizarre rituals intended to bring about th...",`` ... bizarr ritual intend to bring about the...
419,5420,NaN,"""...and the sun became as black as sackcloth. ...",`` ... and the sun becam as black as sackcloth...
420,5421,NaN,"""#Denali, the great one soaring under the midn...","`` # denali , the great one soar under the mid..."
421,5422,NaN,- Just found out season 3 of Arrow is going to...,- just found out season 3 of arrow is go to be...

In [606]:
df['edited_text'] = df['edited_text'].apply(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in word_tokenize(x)]))

In [607]:
df

,Id,Category,Tweet,edited_text
0,1,neutral,Zlatan's 20th goal of the season not enough fo...,zlatan 's 20th goal of the season not enough f...
1,2,positive,Zlatan wears sunglasses so his eyes do not har...,zlatan wear sunglass so hi eye do not harm the...
2,3,positive,Zlatan to Milan may not be the best thing for ...,zlatan to milan may not be the best thing for ...
3,4,positive,Zlatan says he may have played his last match ...,zlatan say he may have play hi last match for ...
4,5,positive,Zlatan is still a beast. If he's replacing RvP...,zlatan is still a beast . if he 's replac rvp ...
...,...,...,...,...
417,5418,NaN,"""@AnishJain50: Sting opens Monday night Raw! #...",`` @ anishjain50 : sting open monday night raw...
418,5419,NaN,"""...bizarre rituals intended to bring about th...",`` ... bizarr ritual intend to bring about the...
419,5420,NaN,"""...and the sun became as black as sackcloth. ...",`` ... and the sun becam a black a sackcloth ....
420,5421,NaN,"""#Denali, the great one soaring under the midn...","`` # denali , the great one soar under the mid..."
421,5422,NaN,- Just found out season 3 of Arrow is going to...,- just found out season 3 of arrow is go to be...

In [608]:
df['edited_text'] = df['edited_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))

In [609]:
df

,Id,Category,Tweet,edited_text
0,1,neutral,Zlatan's 20th goal of the season not enough fo...,zlatan 's 20th goal season enough conced twice...
1,2,positive,Zlatan wears sunglasses so his eyes do not har...,zlatan wear sunglass hi eye harm sun .
2,3,positive,Zlatan to Milan may not be the best thing for ...,"zlatan milan may best thing parti , go un sett..."
3,4,positive,Zlatan says he may have played his last match ...,zlatan say may play hi last match psg . get : ...
4,5,positive,Zlatan is still a beast. If he's replacing RvP...,zlatan still beast . 's replac rvp 's good bus...
...,...,...,...,...
417,5418,NaN,"""@AnishJain50: Sting opens Monday night Raw! #...",`` @ anishjain50 : sting open monday night raw...
418,5419,NaN,"""...bizarre rituals intended to bring about th...","`` ... bizarr ritual intend bring end world , ..."
419,5420,NaN,"""...and the sun became as black as sackcloth. ...",`` ... sun becam black sackcloth . moon becam ...
420,5421,NaN,"""#Denali, the great one soaring under the midn...","`` # denali , great one soar midnight sun `` ...."
421,5422,NaN,- Just found out season 3 of Arrow is going to...,- found season 3 arrow go netflix octob 7th

In [610]:
df['edited_text'] = df['edited_text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

In [611]:
df

,Id,Category,Tweet,edited_text
0,1,neutral,Zlatan's 20th goal of the season not enough fo...,zlatan s 20th goal season enough conced twice ...
1,2,positive,Zlatan wears sunglasses so his eyes do not har...,zlatan wear sunglass hi eye harm sun
2,3,positive,Zlatan to Milan may not be the best thing for ...,zlatan milan may best thing parti go un settl...
3,4,positive,Zlatan says he may have played his last match ...,zlatan say may play hi last match psg get ht...
4,5,positive,Zlatan is still a beast. If he's replacing RvP...,zlatan still beast s replac rvp s good busi h...
...,...,...,...,...
417,5418,NaN,"""@AnishJain50: Sting opens Monday night Raw! #...",anishjain50 sting open monday night raw s...
418,5419,NaN,"""...bizarre rituals intended to bring about th...",bizarr ritual intend bring end world look l...
419,5420,NaN,"""...and the sun became as black as sackcloth. ...",sun becam black sackcloth moon becam blood ...
420,5421,NaN,"""#Denali, the great one soaring under the midn...",denali great one soar midnight sun sarah ...
421,5422,NaN,- Just found out season 3 of Arrow is going to...,found season 3 arrow go netflix octob 7th

In [612]:
from nltk.tokenize import word_tokenize

In [613]:
df['edited_text'] = df['edited_text'].apply(word_tokenize)

In [614]:
df

,Id,Category,Tweet,edited_text
0,1,neutral,Zlatan's 20th goal of the season not enough fo...,"[zlatan, s, 20th, goal, season, enough, conced..."
1,2,positive,Zlatan wears sunglasses so his eyes do not har...,"[zlatan, wear, sunglass, hi, eye, harm, sun]"
2,3,positive,Zlatan to Milan may not be the best thing for ...,"[zlatan, milan, may, best, thing, parti, go, u..."
3,4,positive,Zlatan says he may have played his last match ...,"[zlatan, say, may, play, hi, last, match, psg,..."
4,5,positive,Zlatan is still a beast. If he's replacing RvP...,"[zlatan, still, beast, s, replac, rvp, s, good..."
...,...,...,...,...
417,5418,NaN,"""@AnishJain50: Sting opens Monday night Raw! #...","[anishjain50, sting, open, monday, night, raw,..."
418,5419,NaN,"""...bizarre rituals intended to bring about th...","[bizarr, ritual, intend, bring, end, world, lo..."
419,5420,NaN,"""...and the sun became as black as sackcloth. ...","[sun, becam, black, sackcloth, moon, becam, bl..."
420,5421,NaN,"""#Denali, the great one soaring under the midn...","[denali, great, one, soar, midnight, sun, sara..."
421,5422,NaN,- Just found out season 3 of Arrow is going to...,"[found, season, 3, arrow, go, netflix, octob, ..."

In [615]:
df["Category"].value_counts()

Category
positive    2393
neutral     1794
negative     812
Tweet          1
Name: count, dtype: int64

In [616]:
df.isnull().sum()

Id               0
Category       422
Tweet            0
edited_text      0
dtype: int64

In [617]:
df['Category'].replace('Tweet', 'neutral', inplace=True)

In [618]:
df["Category"].value_counts()

Category
positive    2393
neutral     1795
negative     812
Name: count, dtype: int64

In [619]:
category_mapping = {
    'negative': -1,
    'neutral': 0,
    'positive': 1
}

In [620]:
df['Category_Encoded'] = df['Category'].map(category_mapping)

In [621]:
df

,Id,Category,Tweet,edited_text,Category_Encoded
0,1,neutral,Zlatan's 20th goal of the season not enough fo...,"[zlatan, s, 20th, goal, season, enough, conced...",0.0
1,2,positive,Zlatan wears sunglasses so his eyes do not har...,"[zlatan, wear, sunglass, hi, eye, harm, sun]",1.0
2,3,positive,Zlatan to Milan may not be the best thing for ...,"[zlatan, milan, may, best, thing, parti, go, u...",1.0
3,4,positive,Zlatan says he may have played his last match ...,"[zlatan, say, may, play, hi, last, match, psg,...",1.0
4,5,positive,Zlatan is still a beast. If he's replacing RvP...,"[zlatan, still, beast, s, replac, rvp, s, good...",1.0
...,...,...,...,...,...
417,5418,NaN,"""@AnishJain50: Sting opens Monday night Raw! #...","[anishjain50, sting, open, monday, night, raw,...",NaN
418,5419,NaN,"""...bizarre rituals intended to bring about th...","[bizarr, ritual, intend, bring, end, world, lo...",NaN
419,5420,NaN,"""...and the sun became as black as sackcloth. ...","[sun, becam, black, sackcloth, moon, becam, bl...",NaN
420,5421,NaN,"""#Denali, the great one soaring under the midn...","[denali, great, one, soar, midnight, sun, sara...",NaN
421,5422,NaN,- Just found out season 3 of Arrow is going to...,"[found, season, 3, arrow, go, netflix, octob, ...",NaN

In [622]:
df['Category_Encoded'].value_counts()

Category_Encoded
 1.0    2393
 0.0    1795
-1.0     812
Name: count, dtype: int64

In [623]:
train.shape,test.shape,df.shape

((5000, 3), (422, 2), (5422, 5))

In [624]:
train=df.iloc[:5000,:]
test=df.iloc[5000:,:]

In [625]:
train

,Id,Category,Tweet,edited_text,Category_Encoded
0,1,neutral,Zlatan's 20th goal of the season not enough fo...,"[zlatan, s, 20th, goal, season, enough, conced...",0.0
1,2,positive,Zlatan wears sunglasses so his eyes do not har...,"[zlatan, wear, sunglass, hi, eye, harm, sun]",1.0
2,3,positive,Zlatan to Milan may not be the best thing for ...,"[zlatan, milan, may, best, thing, parti, go, u...",1.0
3,4,positive,Zlatan says he may have played his last match ...,"[zlatan, say, may, play, hi, last, match, psg,...",1.0
4,5,positive,Zlatan is still a beast. If he's replacing RvP...,"[zlatan, still, beast, s, replac, rvp, s, good...",1.0
...,...,...,...,...,...
4995,4996,neutral,.@DIRECTVService Still waiting for an answer r...,"[directvservic, still, wait, answer, regard, s...",0.0
4996,4997,positive,.@brc_222 #brc222 Interesting! It's going to b...,"[brc_222, brc222, interest, s, go, challeng, a...",1.0
4997,4998,negative,..the ramifications may feasibly tear apart th...,"[ramif, may, feasibl, tear, apart, torus, part...",-1.0
4998,4999,positive,..and the search for Cornetto Disc limited edi...,"[search, cornetto, disc, limit, edit, taylor, ...",1.0
4999,5000,negative,...and TGIF!!! What a week... I really dislike...,"[tgif, week, realli, dislik, 1st, 3rd]",-1.0

In [626]:
test

,Id,Category,Tweet,edited_text,Category_Encoded
0,5001,NaN,Zlatan and Wayne welcome to Chicago. Smile for...,"[zlatan, wayn, welcom, chicago, smile, camera,...",NaN
1,5002,NaN,Zlatan = Costa? Zlatan is the 6th best Striker...,"[zlatan, costa, zlatan, 6th, best, striker, wo...",NaN
2,5003,NaN,"Zlatan , will your perfumes make me perform ov...","[zlatan, perfum, make, perform, overhead, kick...",NaN
3,5004,NaN,Zayn? Jlo? Madonna? Selena? Jlo? If we are tal...,"[zayn, jlo, madonna, selena, jlo, talk, icon, ...",NaN
4,5005,NaN,Zayn and Justin are both working in the studio...,"[zayn, justin, work, studio, re, plan, secret,...",NaN
...,...,...,...,...,...
417,5418,NaN,"""@AnishJain50: Sting opens Monday night Raw! #...","[anishjain50, sting, open, monday, night, raw,...",NaN
418,5419,NaN,"""...bizarre rituals intended to bring about th...","[bizarr, ritual, intend, bring, end, world, lo...",NaN
419,5420,NaN,"""...and the sun became as black as sackcloth. ...","[sun, becam, black, sackcloth, moon, becam, bl...",NaN
420,5421,NaN,"""#Denali, the great one soaring under the midn...","[denali, great, one, soar, midnight, sun, sara...",NaN
421,5422,NaN,- Just found out season 3 of Arrow is going to...,"[found, season, 3, arrow, go, netflix, octob, ...",NaN

In [627]:
X=train['edited_text']
y=train['Category_Encoded']

In [628]:
X_test=test['edited_text']
y_test=test['Category_Encoded']

In [629]:
X.shape,y.shape,X_test.shape,y_test.shape

((5000,), (5000,), (422,), (422,))

In [630]:
X

0       [zlatan, s, 20th, goal, season, enough, conced...
1            [zlatan, wear, sunglass, hi, eye, harm, sun]
2       [zlatan, milan, may, best, thing, parti, go, u...
3       [zlatan, say, may, play, hi, last, match, psg,...
4       [zlatan, still, beast, s, replac, rvp, s, good...
                              ...
4995    [directvservic, still, wait, answer, regard, s...
4996    [brc_222, brc222, interest, s, go, challeng, a...
4997    [ramif, may, feasibl, tear, apart, torus, part...
4998    [search, cornetto, disc, limit, edit, taylor, ...
4999               [tgif, week, realli, dislik, 1st, 3rd]
Name: edited_text, Length: 5000, dtype: object

In [631]:
y

0       0.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
4995    0.0
4996    1.0
4997   -1.0
4998    1.0
4999   -1.0
Name: Category_Encoded, Length: 5000, dtype: float64

In [676]:
# Convert each element of X_train to a string
import pandas as pd
from sklearn.model_selection import train_test_split
X = X.astype(str)
X_train, X_test_S, y_train, y_test_S = train_test_split(X,y,test_size=0.3,random_state = 0)
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

pipeline_sgd = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf',  TfidfTransformer()),
    ('clf', SGDClassifier(random_state=0)),
])

model = pipeline_sgd.fit(X_train, y_train)

In [668]:
X_train

2858    ['moonlight', 'sonata', '3rd', 'movement', 'ip...
1559    ['oracl', 'set', 'date', 'first', 'quarter', '...
1441    ['question', 'somebodi', 'settl', 'thi', 'pope...
2179    ['krav', 'maga', 'valentin', 's', 'park', 'ult...
1390    ['result', '1st', '2', 'packet', 'star', 'war'...
                              ...
4931    ['afrouniqu', 'onc', 'sat', 'walgreen', 'park'...
3264    ['first', 'day', 'school', 'tomorrow', 'mean',...
1653    ['oh', 'get', 'joe', 'biden', 'wa', 'someth', ...
2607    ['wenger', 'pari', 'could', 'cavani', 'zlatan'...
2732    ['sat', 'one', 'night', 'n', 'saw', 'thi', 'da...
Name: edited_text, Length: 3500, dtype: object

In [677]:
from sklearn.metrics import classification_report
y_predict_S = model.predict(X_test_S)
print(classification_report(y_test_S, y_predict_S))

              precision    recall  f1-score   support

        -1.0       0.38      0.29      0.33       230
         0.0       0.49      0.41      0.45       557
         1.0       0.64      0.76      0.69       713

    accuracy                           0.56      1500
   macro avg       0.50      0.49      0.49      1500
weighted avg       0.54      0.56      0.55      1500

In [678]:
from sklearn.metrics import accuracy_score # import the module

accuracy =accuracy_score(y_test_S, y_predict_S)
print("Accuracy:", accuracy)

Accuracy: 0.5586666666666666

In [637]:
X_test, y_test

(0      [zlatan, wayn, welcom, chicago, smile, camera,...
 1      [zlatan, costa, zlatan, 6th, best, striker, wo...
 2      [zlatan, perfum, make, perform, overhead, kick...
 3      [zayn, jlo, madonna, selena, jlo, talk, icon, ...
 4      [zayn, justin, work, studio, re, plan, secret,...
                              ...
 417    [anishjain50, sting, open, monday, night, raw,...
 418    [bizarr, ritual, intend, bring, end, world, lo...
 419    [sun, becam, black, sackcloth, moon, becam, bl...
 420    [denali, great, one, soar, midnight, sun, sara...
 421    [found, season, 3, arrow, go, netflix, octob, ...
 Name: edited_text, Length: 422, dtype: object,
 0     NaN
 1     NaN
 2     NaN
 3     NaN
 4     NaN
        ..
 417   NaN
 418   NaN
 419   NaN
 420   NaN
 421   NaN
 Name: Category_Encoded, Length: 422, dtype: float64)

In [ ]:
# X_test= X_test.astype(str)

In [ ]:
X_test

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred={'Tweet':y_pred}

In [ ]:
y_pred=pd.DataFrame(y_pred)

In [ ]:
y_pred

In [ ]:
y_pred.value_counts()

In [ ]:
reverse_mapping = {
    -1.0: 'negative',
    0.0: 'neutral',
    1.0: 'positive'
}

y_pred['Tweet'] = y_pred['Tweet'].map(reverse_mapping)

In [ ]:
y_pred

In [ ]:
y_pred.value_counts()

In [ ]:
submission1= {
    'Id': test['Id'],
    'Tweet': y_pred['Tweet']
}

In [ ]:
submission1=pd.DataFrame(submission1)

In [ ]:
submission1

In [ ]:
submission1['Tweet'].value_counts()

In [ ]:
 submission1.to_csv("submission1.csv",index=False)

In [ ]:
df1=pd.read_csv("/content/submission1.csv")